# Generated by Django 3.0.6 on 2020-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_remove_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='channel',
            field=models.CharField(choices=[('T', 'Telefone'), ('E', 'Email'), ('C', 'Celular')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(default='2222', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
