# Generated by Django 3.0.6 on 2020-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0003_auto_20200519_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='channel',
            field=models.CharField(choices=[('Tel', 'Telefone'), ('Email', 'Email'), ('Cel', 'Celular')], max_length=5),
        ),
    ]
